# Generated by Django 5.1.4 on 2025-01-12 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/additional/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('care_instructions', models.TextField()),
                ('light_requirement', models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('high', 'Bright Light')], max_length=10)),
                ('water_requirement', models.CharField(choices=[('low', 'Low Water'), ('medium', 'Medium Water'), ('high', 'High Water')], max_length=10)),
                ('temperature_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(50)])),
                ('temperature_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(50)])),
                ('humidity_requirement', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mature_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mature_spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_rate', models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], max_length=10)),
                ('main_image', models.ImageField(upload_to='plants/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('additional_images', models.ManyToManyField(blank=True, to='plants.plantimage')),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('size', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'verbose_name_plural': 'Plant inventories',
                'unique_together': {('plant', 'nursery', 'size')},
            },
        ),
    ]
