# Generated by Django 5.1.4 on 2025-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='deer_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='drought_tolerant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='edible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizer_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='flowering_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='flowering_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='fragrant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruiting_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='hardiness_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='indoor_suitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='native_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='pest_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='time_to_maturity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plantinventory',
            name='seasonal_availability',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mature_height',
            field=models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mature_spread',
            field=models.DecimalField(decimal_places=2, help_text='Spread in centimeters', max_digits=5),
        ),
    ]
