# Generated by Django 5.1.4 on 2025-01-20 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_deer_resistant_plant_drought_tolerant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='care_instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='fertilizer_requirements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='flowering_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='flowering_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='fruiting_season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('year_round', 'Year Round')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_rate',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='hardiness_zone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity_requirement',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light_requirement',
            field=models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('high', 'Bright Light')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/main/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mature_height',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Height in centimeters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mature_spread',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Spread in centimeters', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plant',
            name='native_region',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planting_instructions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_type',
            field=models.CharField(default='All purpose potting mix', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_max',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_min',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='time_to_maturity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_requirement',
            field=models.CharField(choices=[('low', 'Low Water'), ('medium', 'Medium Water'), ('high', 'High Water')], default='medium', max_length=10),
        ),
    ]
