# Generated by Django 5.1.4 on 2025-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_featured_plant_price_plant_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('perennials', 'Perennials'), ('annuals', 'Annuals'), ('shrubs', 'Shrubs'), ('trees', 'Trees'), ('vines', 'Vines'), ('indoor', 'Indoor Plants'), ('succulents', 'Succulents & Cacti'), ('herbs', 'Herbs'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grasses', 'Ornamental Grasses')], default='perennials', max_length=20),
        ),
    ]
